-- filter.sql: WHERE clause for rebuilding the candidates table.
-- Edit this file, then run `python -m autoapply.filter` to apply.

-- Location
j.country IN ('US', 'CA')

-- Employment type (NULLs pass — Greenhouse doesn't provide this)
AND (j.employment_type = 'full-time' OR j.employment_type IS NULL)

-- Title must contain a software-ish keyword
AND (j.title LIKE '%engineer%' OR j.title LIKE '%developer%'
     OR j.title LIKE '%scientist%' OR j.title LIKE '%architect%'
     OR j.title LIKE '%researcher%'
     OR j.title LIKE '%member of technical%'
     OR j.title LIKE '%data analyst%')

-- Seniority excludes
AND j.title NOT LIKE '%senior%'
AND j.title NOT LIKE 'sr %'
AND j.title NOT LIKE '% sr %'
AND j.title NOT LIKE 'sr.%'
AND j.title NOT LIKE '% sr.%'
AND j.title NOT LIKE '% sr'
AND (j.title NOT LIKE '%staff%' OR j.title LIKE '%member of technical staff%')
AND j.title NOT LIKE '%principal%'
AND j.title NOT LIKE '%director%'
AND j.title NOT LIKE '%manager%'
AND j.title NOT LIKE '%lead %'
AND j.title NOT LIKE '%lead,%'
AND j.title NOT LIKE '%, lead'
AND j.title NOT LIKE '%vp,%'
AND j.title NOT LIKE '%vp %'
AND j.title NOT LIKE '%vice president%'
AND j.title NOT LIKE '%head of%'
AND j.title NOT LIKE '%phd%'
AND j.title NOT LIKE '%distinguished%'
AND j.title NOT LIKE '%expert%'
AND j.title NOT LIKE '%intern%'
AND j.title NOT LIKE '%cleared%'
AND j.title NOT LIKE '%ts/sci%'
AND j.title NOT LIKE '%clearance%'
AND j.title NOT LIKE '%chief engineer%'

-- Non-software title excludes
AND j.title NOT LIKE '%mechanical%'
AND j.title NOT LIKE '%electrical%'
AND j.title NOT LIKE '%civil%'
AND j.title NOT LIKE '%structural%'
AND j.title NOT LIKE '%chemical%'
AND j.title NOT LIKE '%manufacturing%'
AND j.title NOT LIKE '%industrial%'
AND j.title NOT LIKE '%construction%'
AND j.title NOT LIKE '%building engineer%'
AND j.title NOT LIKE '%hvac%'
AND j.title NOT LIKE '%piping%'
AND j.title NOT LIKE '%welding%'
AND j.title NOT LIKE '%maintenance%'
AND j.title NOT LIKE '%field service%'
AND j.title NOT LIKE '%field engineer%'
AND j.title NOT LIKE '%process engineer%'
AND j.title NOT LIKE '%project engineer%'
AND j.title NOT LIKE '%design engineer%'
AND j.title NOT LIKE '%controls engineer%'
AND j.title NOT LIKE '%power engineer%'
AND j.title NOT LIKE '%thermal%'
AND j.title NOT LIKE '%nurse%'
AND j.title NOT LIKE '%veterinar%'
AND j.title NOT LIKE '%dental%'
AND j.title NOT LIKE '%therapist%'
AND j.title NOT LIKE '%physician%'
AND j.title NOT LIKE '%clinical%'
AND j.title NOT LIKE '%psycholog%'
AND j.title NOT LIKE '%mammograph%'
AND j.title NOT LIKE '%technician%'
AND j.title NOT LIKE '%hardware%'
AND j.title NOT LIKE '%embedded%'
AND j.title NOT LIKE '%firmware%'
AND j.title NOT LIKE '%robotics%'
AND j.title NOT LIKE '%audio%'
AND j.title NOT LIKE '%geotechnical%'
AND j.title NOT LIKE '%mechatronics%'
AND j.title NOT LIKE '%equipment engineer%'
AND j.title NOT LIKE '%environmental%'
AND j.title NOT LIKE '%materials%'
AND j.title NOT LIKE '%nuclear%'
AND j.title NOT LIKE '%optical%'
AND j.title NOT LIKE '%rf engineer%'
AND j.title NOT LIKE '%signal%'
AND j.title NOT LIKE '%packaging%'
AND j.title NOT LIKE '%safety engineer%'
AND j.title NOT LIKE '%commissioning%'
AND j.title NOT LIKE '%biomedical%'
AND j.title NOT LIKE '%marine engineer%'
AND j.title NOT LIKE '%naval%'
AND j.title NOT LIKE '%plumbing%'
AND j.title NOT LIKE '%acoustic%'
AND j.title NOT LIKE '%site engineer%'
AND j.title NOT LIKE '%project architect%'

-- Non-software role excludes
AND j.title NOT LIKE '%sales engineer%'
AND j.title NOT LIKE '%support engineer%'
AND j.title NOT LIKE '%customer success%'
AND j.title NOT LIKE '%network engineer%'
AND j.title NOT LIKE '%validation engineer%'
AND j.title NOT LIKE '%gtm engineer%'
AND j.title NOT LIKE '%it engineer%'
AND j.title NOT LIKE '%it operations%'
AND j.title NOT LIKE '%it systems%'
AND j.title NOT LIKE '%enterprise architect%'
AND j.title NOT LIKE '%quality assurance%'
AND j.title NOT LIKE '%quality engineer%'
AND j.title NOT LIKE '%test engineer%'
AND j.title NOT LIKE '%power bi%'
AND j.title NOT LIKE '%sharepoint%'
AND j.title NOT LIKE '%fpga%'
AND j.title NOT LIKE '%power electronics%'
AND j.title NOT LIKE '%job captain%'
AND j.title NOT LIKE '%supplier development%'
AND j.title NOT LIKE '%fire protection%'
AND j.title NOT LIKE '%facilities engineer%'
AND j.title NOT LIKE '%aircraft engineer%'
AND j.title NOT LIKE '%transportation engineer%'
AND j.title NOT LIKE '%fsr engineer%'
AND j.title NOT LIKE '%commvault%'
AND j.title NOT LIKE '%onestream%'
AND j.title NOT LIKE '%netsuite%'
AND j.title NOT LIKE 'architect'

-- Company exclusions
AND j.company_name NOT LIKE '%spacex%'
AND j.company_name NOT LIKE '%Accenture Federal%'
